apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: todo-app-pkg.kamloiic.github.com.1.0.0
spec:
  refName: todo-app-pkg.kamloiic.github.com
  version: 1.0.0
  releaseNotes: |
    first release of the todo service
  
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: ghcr.io/kamloiic/todo-app-pkg@sha256:b48869383a53726acd2c085386846ceb0f2aa17014ff015f37da0d32ecdf0c7b
      template:
        - ytt:
            paths:
              - "config/"
        - kbld:
            paths:
              - "-"
              - ".imgpkg/images.yml"
      deploy:
        - kapp: {}