apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: todo-app-pkg.kamloiic.github.com.1.0.0
spec:
  refName: todo-app-pkg.kamloiic.github.com
  version: 1.0.0
  releaseNotes: |
    first release of the todo service
  
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: ghcr.io/kamloiic/todo-app-pkg@sha256:10632b639ec0442e7731bf4d67a8a37868a97aa4ec6befe37a729f53ac6a0bf4
      template:
        - ytt:
            paths:
              - "config/"
        - kbld:
            paths:
              - "-"
              - ".imgpkg/images.yml"
      deploy:
        - kapp: {}