version: '3'

services:
  db:
    container_name: db
    image: postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment: 
      - POSTGRES_USER=taskuser
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=task
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  
  backend: 
    container_name: backend
    build: ./backend 
    ports:
      - "8080:8080"
    links:
      - db
    restart: unless-stopped


  frontend:
    container_name: frontend
    build: ./frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    links:
      - backend
    

volumes:
  postgresql_data:
    driver: local




    


   
