version: '3.1'

services:
    
    postgres:
      image: postgres:latest
      network_mode: bridge
      container_name: postgres
      expose:
      - 5432
      ports:
        - 5432:5432
      environment:
          - POSTGRES_PASSWORD=loic
          - POSTGRES_USER=loic
          - POSTGRES_DB=task
    todoapp:
      image: todoapp:latest
      network_mode: bridge
      container_name: todoapp
      expose:
        - 8080
      ports:
        - 8080:8080
      restart: unless-stopped
      depends_on:
        - postgres
      links:
        - postgres

volumes:
  postgres-data: 


   
