---
apiVersion: imgpkg.carvel.dev/v1alpha1
images:
- annotations:
    kbld.carvel.dev/id: ghcr.io/kamloiic/todo-backend:latest
    kbld.carvel.dev/origins: |
      - resolved:
          tag: latest
          url: ghcr.io/kamloiic/todo-backend:latest
  image: ghcr.io/kamloiic/todo-backend@sha256:6ffaea0947c52cef8b86b4f6aa53d2da72798b68b19c1fcb68a793ac6575653c
- annotations:
    kbld.carvel.dev/id: ghcr.io/kamloiic/todo-frontend:latest
    kbld.carvel.dev/origins: |
      - resolved:
          tag: latest
          url: ghcr.io/kamloiic/todo-frontend:latest
  image: ghcr.io/kamloiic/todo-frontend@sha256:590a67d4ec90cda59b3a554f3f5984075f34ed4455afb25337627b04e87c6476
kind: ImagesLock
