#kubectl -n todo-kpack create secret docker-registry ghcr-creditentials --docker-server=ghcr.io --docker-username=kamloiic --docker-password=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  --docker-email=lkameni@vmware.com
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-account
  namespace: todo-kpack
secrets:
- name: ghcr-creditentials
imagePullSecrets:
- name: ghcr-creditentials