apiVersion: kpack.io/v1alpha2
kind: ClusterBuilder
metadata:
  name: todo-builder
spec:
  tag: ghcr.io/kamloiic/todo-builder    
  serviceAccountRef:
    name: service-account
    namespace: todo-kpack
  stack:
    kind: ClusterStack
    name: todo-stack
  store:
    kind: ClusterStore
    name: todo-store
  order:
  - group:
    - id: paketo-buildpacks/java
  - group:
    - id: paketo-buildpacks/nodejs