apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  name: todo-app-image
  namespace: default
spec:
  tag: todo-app-backend
  serviceAccountName: service-account
  builder:
    name: my-builder
    kind: Builder
  source:
    git:
      url: https://github.com/kamloiic/todo-app/tree/main/backend.git
      revision: 82cb521d636b282340378d80a6307a08e3d4a4c4