
name: CI

on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    name: Build, push and deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout main 
      uses: actions/checkout@main

    - name: Login to Github Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        passwork: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push React Image 
      run: |
        docker build ./frontend --tag ghcr.io/kamloiic/todo-frontend:latest
        docker run ghcr.io/kamloiic/todo-frontend:latest
        docker push ghcr.io/kamloiic/todo-frontend:latest
        
    - name: Build and push Spring Boot Image
      run: |
        docker build ./backend --tag ghcr.io/kamloiic/todo-backend:latest
        docker run ghcr.io/kamloiic/todo-backend:latest
        docker push ghcr.io/kamloiic/todo-backend:latest
